### ISSUE TITLE
[Errno 8] Exec format error while trying to make sdcard for unified launcher

### ISSUE THREAD

**Issue by jin** [google/android-testing-support-library#36]
Command:

```
bazel build @android_test_support//tools/android/emulated_devices/pixel:google_25_x86_qemu2
```

Stacktrace:

``` 
I1011 18:16:44.618 emulated_device.py:650]trying to make sdcard on the fly.
I1011 18:16:44.927 emulated_device.py:271]Emulator type: 2
 creating android images...; 3s linux-sandbox

 18:16:45.039 emulated_device.py:1658]Executing: ['/usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/c3fd10e8f98dec3345138bf677d22ccd/bazel-sandbox/5716239700482091081/execroot/__main__/external/androidsdk/emulator/emulator', '-ports', '23546,22441', '-skin', '540x960', '-cache', 'cache.img', '-data', 'userdata-qemu.img', '-memory', '4096', '-sdcard', 'sdcard.img', '-partition-size', '2047', '-no-snapshot-save', '-verbose', '-unix-pipe', 'sockets/qemu.mgmt', '-unix-pipe', 'sockets/device-forward-server', '-unix-pipe', 'sockets/tar-pull-server', '-unix-pipe', 'sockets/exec-server', '-unix-pipe', 'sockets/tar-push-server', '-writable-system', '-show-kernel', '-engine', 'qemu2', '-kernel', '/tmp/tmpTluMI7android-emulator-launch/images/init/kernel-ranchu', '-no-window', '-gpu', 'on', '-no-audio', '-no-boot-anim', '-selinux', 'permissive', '-fixed-scale', '-netdelay', 'none', '-netspeed', 'full', '-avd', 'mobile_ninjas.adb.22441', '-qemu', '-enable-kvm', '-L', '/tmp/tmpTluMI7android-emulator-launch/bios']
I1011 18:16:45.042 emulated_device.py:1673]Launching emulator in: /tmp/tmpTluMI7android-emulator-launch/images/session
I1011 18:16:45.043 emulated_device.py:1679]Write emulator log to /tmp/emulator_logVKuIjB.txt
I1011 18:16:45.043 emulated_device.py:2125]system: False pm: False adb: False sdcard: False boot_complete: False launcher: False pipes: False current step attempts: 0 total attempts: 0
I1011 18:16:45.043 emulated_device.py:3473]Checking if adb is listening.
I1011 18:16:45.294 emulated_device.py:2125]system: False pm: False adb: False sdcard: False boot_complete: False launcher: False pipes: False current step attempts: 1 total attempts: 1
I1011 18:16:45.295 emulated_device.py:3427]Emulator log below ==================================================

I1011 18:16:45.295 emulated_device.py:3428]Emulator log end ==================================================
I1011 18:16:45.295 emulated_device.py:3427]watchdog.out below ==================================================
If you want to add certificates to the emulator, Please install MCrypt library using sudo apt-get install python-mcrypt .

I1011 18:16:45.295 emulated_device.py:3428]watchdog.out end ==================================================
I1011 18:16:45.295 emulated_device.py:3427]watchdog.err below ==================================================
Traceback (most recent call last):
  File "/usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/c3fd10e8f98dec3345138bf677d22ccd/bazel-sandbox/5716239700482091081/execroot/__main__/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/__main__/../android_test_support/tools/android/emulator/unified_launcher.py", line 958, in <module>
    app.run()
  File "/usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/c3fd10e8f98dec3345138bf677d22ccd/bazel-sandbox/5716239700482091081/execroot/__main__/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/google_apputils/google/apputils/app.py", line 238, in run
    return _actual_start()
  File "/usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/c3fd10e8f98dec3345138bf677d22ccd/bazel-sandbox/5716239700482091081/execroot/__main__/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/google_apputils/google/apputils/app.py", line 267, in _actual_start
    really_start()
  File "/usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/c3fd10e8f98dec3345138bf677d22ccd/bazel-sandbox/5716239700482091081/execroot/__main__/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/google_apputils/google/apputils/app.py", line 220, in really_start
    sys.exit(main(argv))
  File "/usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/c3fd10e8f98dec3345138bf677d22ccd/bazel-sandbox/5716239700482091081/execroot/__main__/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/__main__/../android_test_support/tools/android/emulator/unified_launcher.py", line 941, in main
    EntryPoint(reporter)
  File "/usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/c3fd10e8f98dec3345138bf677d22ccd/bazel-sandbox/5716239700482091081/execroot/__main__/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/__main__/../android_test_support/tools/android/emulator/unified_launcher.py", line 778, in EntryPoint
    boot_time_apks)
  File "/usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/c3fd10e8f98dec3345138bf677d22ccd/bazel-sandbox/5716239700482091081/execroot/__main__/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/__main__/../android_test_support/tools/android/emulator/unified_launcher.py", line 311, in _FirstBootAtBuildTimeOnly
    build_time_only_no_op_rendering=True)
  File "/usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/c3fd10e8f98dec3345138bf677d22ccd/bazel-sandbox/5716239700482091081/execroot/__main__/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/android_test_support/tools/android/emulator/emulated_device.py", line 1167, in StartDevice
    with_audio, with_boot_anim)
  File "/usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/c3fd10e8f98dec3345138bf677d22ccd/bazel-sandbox/5716239700482091081/execroot/__main__/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/android_test_support/tools/android/emulator/emulated_device.py", line 1686, in _StartEmulator
    pipe_dir)
  File "/usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/c3fd10e8f98dec3345138bf677d22ccd/bazel-sandbox/5716239700482091081/execroot/__main__/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/android_test_support/tools/android/emulator/emulated_device.py", line 1754, in _ForkWatchdog
    pipe_dir)
  File "/usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/c3fd10e8f98dec3345138bf677d22ccd/bazel-sandbox/5716239700482091081/execroot/__main__/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/android_test_support/tools/android/emulator/emulated_device.py", line 1778, in _WatchdogLoop
    pipe_service_processes = self._StartPipeServices(pipe_dir)
  File "/usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/c3fd10e8f98dec3345138bf677d22ccd/bazel-sandbox/5716239700482091081/execroot/__main__/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/android_test_support/tools/android/emulator/emulated_device.py", line 1931, in _StartPipeServices
    close_fds=True))
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

I1011 18:16:45.295 emulated_device.py:3428]watchdog.err end ==================================================
Traceback (most recent call last):
  File "/usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/c3fd10e8f98dec3345138bf677d22ccd/bazel-sandbox/5716239700482091081/execroot/__main__/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/__main__/../android_test_support/tools/android/emulator/unified_launcher.py", line 958, in <module>
    app.run()
  File "/usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/c3fd10e8f98dec3345138bf677d22ccd/bazel-sandbox/5716239700482091081/execroot/__main__/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/google_apputils/google/apputils/app.py", line 238, in run
    return _actual_start()
  File "/usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/c3fd10e8f98dec3345138bf677d22ccd/bazel-sandbox/5716239700482091081/execroot/__main__/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/google_apputils/google/apputils/app.py", line 267, in _actual_start
    really_start()
  File "/usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/c3fd10e8f98dec3345138bf677d22ccd/bazel-sandbox/5716239700482091081/execroot/__main__/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/google_apputils/google/apputils/app.py", line 220, in really_start
    sys.exit(main(argv))
  File "/usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/c3fd10e8f98dec3345138bf677d22ccd/bazel-sandbox/5716239700482091081/execroot/__main__/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/__main__/../android_test_support/tools/android/emulator/unified_launcher.py", line 941, in main
    EntryPoint(reporter)
creating android images...; 3s linux-sandbox

File "/usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/c3fd10e8f98dec3345138bf677d22ccd/bazel-sandbox/5716239700482091081/execroot/__main__/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/__main__/../android_test_support/tools/android/emulator/unified_launcher.py", line 778, in EntryPoint
    boot_time_apks)
  File "/usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/c3fd10e8f98dec3345138bf677d22ccd/bazel-sandbox/5716239700482091081/execroot/__main__/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/__main__/../android_test_support/tools/android/emulator/unified_launcher.py", line 311, in _FirstBootAtBuildTimeOnly
    build_time_only_no_op_rendering=True)
  File "/usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/c3fd10e8f98dec3345138bf677d22ccd/bazel-sandbox/5716239700482091081/execroot/__main__/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/android_test_support/tools/android/emulator/emulated_device.py", line 1167, in StartDevice
    with_audio, with_boot_anim)
  File "/usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/c3fd10e8f98dec3345138bf677d22ccd/bazel-sandbox/5716239700482091081/execroot/__main__/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/android_test_support/tools/android/emulator/emulated_device.py", line 1690, in _StartEmulator
    self._PollEmulatorStatus(timer)
  File "/usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/c3fd10e8f98dec3345138bf677d22ccd/bazel-sandbox/5716239700482091081/execroot/__main__/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/android_test_support/tools/android/emulator/emulated_device.py", line 2126, in _PollEmulatorStatus
    self._EnsureEmuRunning()
  File "/usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/c3fd10e8f98dec3345138bf677d22ccd/bazel-sandbox/5716239700482091081/execroot/__main__/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/android_test_support/tools/android/emulator/emulated_device.py", line 3447, in _EnsureEmuRunning
    raise Exception('Emulator has died')
Exception: Emulator has died
 creating android images...; 3s linux-sandbox

Target @android_test_support//tools/android/emulated_devices/pixel:google_25_x86_qemu2 failed to build
 no action running

Use --verbose_failures to see the command lines of failed build steps.
no action running

Elapsed time: 53.406s, Critical Path: 26.41s
no action running

FAILED: Build did NOT complete successfully
```

**Comment by aj-michael** [comment]
The issue is default_sdcard_256.img.tag.gz contains third_party/android/android_test_support/tools/android/emulator/support/default_sdcard.256.img instead of android_test_support/tools/android/emulator/support/default_sdcard.256.img

**Comment by jin** [comment]
@aj-michael that causes the IOError to raise, but the root cause of this breakage (`OSError: [Errno 8] Exec format error`) is because of the binary diffs, as you mentioned earlier.

**Comment by jin** [comment]
Drilling down: pipe_traversal and adb.turbo binaries are affected.
